[build]
  # Directorio base del proyecto
  base = "Frontend/waycombat-frontend"
  # Directorio donde se publica la aplicación construida
  publish = "dist/waycombat-frontend/browser"
  # Comando de build para Netlify - usar npx para garantizar disponibilidad de Angular CLI
  command = "npm install --include=dev && npx ng build --configuration=production"

# Variables de entorno para el build
[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"
  NODE_ENV = "production"

# Redirects para Single Page Application (SPA)
# Esto es crucial para que Angular routing funcione correctamente
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers de seguridad
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Headers específicos para archivos estáticos
[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.woff2"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Headers para el archivo principal (menos cache)
[[headers]]
  for = "/index.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"