[build][build]

  base = "Frontend/waycombat-frontend"  publish = "Frontend/waycombat-frontend/dist/waycombat-frontend/browser"

  publish = "Frontend/waycombat-frontend/dist/waycombat-frontend"  command = "cd Frontend/waycombat-frontend && npm install --include=dev && npx ng build --configuration=production"

  command = "npm install --include=dev && npx ng build --configuration=production"

  functions = "../../netlify/functions"[build.environment]

  NODE_VERSION = "18"

[build.environment]  NODE_ENV = "production"

  NODE_ENV = "production"

[[redirects]]

[[redirects]]  from = "/*"

  from = "/api/*"  to = "/index.html"

  to = "/.netlify/functions/:splat"  status = 200
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200