[build]
  publish = "Frontend/waycombat-frontend/dist/waycombat-frontend/browser"
  command = "cd Frontend/waycombat-frontend && npm install --include=dev && npx ng build --configuration=production"

[build.environment]
  NODE_VERSION = "18"
  NODE_ENV = "production"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200