[build]
  base = "Frontend/waycombat-frontend"
  publish = "dist/waycombat-frontend/browser"
  command = "npm install --include=dev && npx ng build --configuration=production && cd ../../netlify && npm install"
  functions = "../../netlify/functions"

[build.environment]
  NODE_ENV = "production"

[functions]
  external_node_modules = ["@netlify/neon", "bcryptjs", "jsonwebtoken"]

# Comentamos la redirección general para usar las específicas del _redirects
# [[redirects]]
#   from = "/api/*"
#   to = "/.netlify/functions/:splat"
#   status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200