[build]
  publish = "Frontend/waycombat-frontend/dist/waycombat-frontend/browser"
  command = "cd Frontend/waycombat-frontend && npm ci && npm run build"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200