services:
  - type: web
    name: waycombat-api
    runtime: docker
    dockerfilePath: ./Backend/WayCombat.Api/Dockerfile
    dockerContext: ./Backend/WayCombat.Api
    env: ASPNETCORE_ENVIRONMENT=Production
    plan: free
    healthCheckPath: /health
    autoDeploy: true
    buildFilter:
      paths:
        - Backend/**
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: ASPNETCORE_URLS
        value: http://+:$PORT
      - key: PORT
        value: 8080
      - key: JWT_KEY
        generateValue: true
      - key: PRODUCTION_ORIGIN
        value: https://waycombat.netlify.app
      - key: DATABASE_URL
        fromDatabase:
          name: waycombat-postgres
          property: connectionString

databases:
  - name: waycombat-postgres
    databaseName: waycombat_prod
    user: waycombat_user
    plan: free