services:
  # Backend API - WayCombat
  - type: web
    name: waycombat-api
    runtime: docker
    repo: https://github.com/Camilo-Silva/WayCombat.git
    branch: produccion
    dockerfilePath: ./Dockerfile
    dockerContext: ./Backend/WayCombat.Api
    region: oregon
    plan: starter
    autoDeploy: true
    healthCheckPath: /health
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: PORT
        value: 8080
      - key: DATABASE_PATH
        value: /app/data/waycombat_dev.db
      - key: CORS_ORIGINS
        generateValue: true
        # Se configurar치 autom치ticamente con el dominio de Render
    # Volumes persistentes para SQLite
    disk:
      name: waycombat-data
      mountPath: /app/data
      sizeGB: 1

  # Frontend Angular - Solo para referencia (se desplegar치 por separado en Netlify/Vercel)
  # - type: static
  #   name: waycombat-frontend
  #   runtime: node
  #   repo: https://github.com/Camilo-Silva/WayCombat.git
  #   branch: produccion
  #   buildCommand: cd Frontend/waycombat-frontend && npm install && npm run build:prod
  #   publishDir: Frontend/waycombat-frontend/dist/waycombat-frontend
  #   envVars:
  #     - key: NODE_ENV
  #       value: production

# Configuraci칩n de red
networks:
  - name: waycombat-network
    region: oregon